services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: blend
      POSTGRES_PASSWORD: blend
      POSTGRES_DB: blendin
    volumes:
      - blendin_pg_data:/var/lib/postgresql/data

volumes:
  blendin_pg_data:
